# SPDX-License-Identifier: MIT
---
description: |
  Custom ZMK behavior that presses two bindings when its combo fires.
  The *quick* binding is released on the first key-up of the combo while
  the *slow* binding is held until the last key-up.

compatible: "zmk,behavior-dual-release-combo"

include: base.yaml

properties:
  "#binding-cells":
    type: int
    const: 0
    description: |
      This behaviour is referenced without additional cells.