# SPDX-License-Identifier: MIT
---
title: Dual Release Combo Behavior

description: |
  Custom ZMK behavior that presses two bindings when its combo fires.
  The *quick* binding is released on the first key-up of the combo while
  the *slow* binding is held until the last key-up.

compatible: "zmk,behavior-dual-release-combo"

include: base.yaml

properties:
  "#binding-cells":
    const: 2
    description: |
      Number of cells in a binding.  Must be **2** where:
        0 – slow-release binding
        1 – quick-release binding 