manifest:
  remotes:
    - name: harlord
      url-base: https://github.com/harlord
  projects:
    - name: zmk
      remote: harlord
      revision: main
      import: app/west.yml
  self:
    path: config
